config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  # BEGIN CUSTOM DEVISE ROUTES #
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "8626705366" }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "8626705366", to: "devise/registrations#new"
  end
  # END CUSTOM DEVISE ROUTES #
  scope "/admin" do
    resources :users, except: [:show]
  end

  resources :posts, only: [:show]
  resources :admin, only: [:index]

  get 'get_posts' => 'posts#get_posts', :as => :get_posts
  get 'slideshow' => 'posts#slideshow', :as => :slideshow
  get 'random_winner' => 'posts#random_winner', :as => :random_winner

  namespace :api do
    namespace :v1 do
      resources :campaigns do
        resources :posts, only: [:show]
      end
    end
  end

  resources :campaigns, only: [:index, :create]
  resources :campaigns, path: '', except: [:index, :create] do
    resources :posts, only: [:create, :destroy]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :require_login

	def index
    @user = current_user
	end

  private

  def require_login
    unless current_user
      redirect_to login_url
    end
  end

end

app/views/welcome/index.html.erb
<main class="landing">
  <div class="parallax-container">
    <div class="parallax valign-wrapper">
      <img src="https://s3.amazonaws.com/rdugc/assets/abstractblue.jpg">
      <div class="container valign">
        <div class="row">
          <div class="col s12">
            <h1 class="text-z-depth-1">Create a new contest</h1>
          </div>
          <div class="col s12">
            <%= link_to 'New Campaign', new_campaign_path, class: 'waves-effect waves-light btn grey darken-4 admin-link z-depth-1' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax valign-wrapper">
      <img src="https://s3.amazonaws.com/rdugc/assets/redabstract.jpg">
      <div class="container valign">
        <div class="row">
          <div class="col s12 right-align">
            <h1 class="text-z-depth-1">View all contests</h1>
          </div>
          <div class="col s12 right-align">
            <%= link_to 'View Campaigns', campaigns_path, class: 'waves-effect waves-light btn grey darken-4 admin-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-container">
    <div class="parallax valign-wrapper">
      <img src="https://s3.amazonaws.com/rdugc/assets/greenabstract.jpg">
      <div class="container valign">
        <div class="row">
          <div class="col s12">
            <h1 class="text-z-depth-1">Add a team member</h1>
          </div>
          <div class="col s12">
            <%= link_to 'Create an Admin', admin_index_path, class: 'waves-effect waves-light btn grey darken-4 admin-link' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>