config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  # BEGIN CUSTOM DEVISE ROUTES #
  devise_for :users, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "8626705366" }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "8626705366", to: "devise/registrations#new"
  end
  # END CUSTOM DEVISE ROUTES #
  scope "/admin" do
    resources :users, except: [:show]
  end

  resources :posts, only: [:show]
  resources :admin, only: [:index]

  get 'get_posts' => 'posts#get_posts', :as => :get_posts
  get 'slideshow' => 'posts#slideshow', :as => :slideshow
  get 'random_winner' => 'posts#random_winner', :as => :random_winner

  namespace :api do
    namespace :v1 do
      resources :campaigns do
        resources :posts, only: [:show]
      end
    end
  end

  resources :campaigns, only: [:index, :create]
  resources :campaigns, path: '', except: [:index, :create] do
    resources :posts, only: [:create, :destroy]
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	has_many :posts
	extend FriendlyId
	friendly_id :title, use: :slugged
	mount_uploader :feature, FeatureUploader
	process_in_background :feature
	mount_uploader :video, VideoUploader
	process_in_background :video
	validates_presence_of :title
	validates_presence_of :description
	validates_presence_of :call_to_action

	def should_generate_new_friendly_id?
	  title_changed?
	end

  def normalize_friendly_id(string)
		super.gsub("-", "")
	end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  respond_to :html, :js
  include ApplicationHelper

  def index
    @user = current_user
    if user_admin(@user)
      @campaigns = Campaign.all
    else
      not_found
    end
  end

  def show
    @campaign = Campaign.friendly.find(params[:id])
    @duration_limit = Time.at(@campaign.duration_limit).utc.strftime("%M:%S")
    @user = current_user
    unless @campaign.live
      unless user_admin(@user)
        not_found
      end
    end
    if params[:search]
      @posts = @campaign.posts.search(params[:search]).paginate(:page => params[:page], :per_page => 12).order('created_at DESC')
    else
      @posts = @campaign.posts.paginate(:page => params[:page], :per_page => 12).order('created_at DESC')
    end
  end

  def new
    @user = current_user
    if user_admin(@user)
      @campaign = Campaign.new
    else
      not_found
    end
  end

  def create
    @user = current_user
    if user_admin(@user)
      modified_params = feature_priority(campaign_params)
      @campaign = Campaign.new(modified_params)
      title = @campaign.title

      if @campaign.save
        flash[:notice] = "Your new campaign '#{title}' was created!"
        redirect_to @campaign
      else
        flash[:error] = "There was an error creating the campaign. Please try again."
        render action: :new
      end
    else
      not_found
    end
  end

  def edit
    @user = current_user
    if user_admin(@user)
      @campaign = Campaign.friendly.find(params[:id])
    else
      not_found
    end
  end

  def update
    @user = current_user
    if user_admin(@user)
      @campaign = Campaign.friendly.find(params[:id])
      modified_params = feature_priority(campaign_params, @campaign)
      title = @campaign.title
      if @campaign.update_attributes(modified_params)
        flash[:notice] = "The campaign '#{title}' was updated!"
        redirect_to @campaign
      else
        flash[:error] = "There was an error updating the campaign. Please try again."
        render action: :edit
      end
    else
      not_found
    end
  end

  def destroy
    @user = current_user
    if user_admin(@user)
      @campaign = Campaign.friendly.find(params[:id])
      title = @campaign.title

      if @campaign.destroy
        flash[:notice] = "The campaign '#{title}' was deleted successfully."
        redirect_to @campaign
      else
        flash[:error] = "There was an error deleting the campaign '#{title}'. Please try again."
        render :show
      end
    else
      not_found
    end
  end

  private

  def feature_priority(modified_params, campaign = nil)
    modified_params = modified_params.dup
    if modified_params['video']
      campaign.remove_feature! unless campaign.nil?
      modified_params.delete('feature')
      modified_params.delete('feature_cache')
    elsif modified_params['feature']
      campaign.remove_video! unless campaign.nil?
      modified_params.delete('video')
      modified_params.delete('video_cache')
    end
    return modified_params
  end

  def campaign_params
    params.require(:campaign).permit(:title,
      :description,
      :call_to_action,
      :feature,
      :feature_cache,
      :video,
      :video_cache,
      :live,
      :slug,
      :analytics,
      :email_recipients,
      :email_notifications,
      :campaign_type,
      :duration_limit,
      :entries_visible,
      :top_color,
      :bottom_color,
      :text_color,
      :text_shadow)
  end

end

app/views/campaigns/_admintools.html.erb
<div id="admin-tools" class="row">
  <div class="col s10 offset-s1 card large hoverable">
    <div class="col s12 m6 l5 offset-l1">
      <h4>Admin Tools</h4>
    </div>
    <div class="col s12 m6 l4 offset-l2">
      <h4>
        <div class="switch">
          <label>
            Help Off
            <input id="helpers" type="checkbox">
            <span id="helper-lever" class="lever"></span>
            Help On
          </label>
        </div>
      </h4>
    </div>
    <div class="col s12 center-align">
      <%= link_to get_posts_path(campaign_id: @campaign.id, format: "csv"), class: 'col s12 m6 l2 offset-l1 btn waves-effect waves-light blue accent-3', :data => { :position => "top", :delay => "50", :tooltip => "Download all entries from #{@campaign.title}" } do %>
        <i class="fa fa-cloud-download"></i> ENTRIES
      <% end %>
      <%= link_to edit_campaign_path(@campaign), class: 'col s12 m6 l2 btn waves-effect waves-light purple darken-3', :data => { :position => "bottom", :delay => "50", :tooltip => "Edit #{@campaign.title}" } do %>
        <i class="fa fa-pencil"></i> <%= "EDIT" %>
      <% end %>
      <% if @campaign.live %>
        <%= simple_form_for @campaign, html: { class: "col s12 m6 l2 stop-campaign"} do |f| %>
          <%= f.check_box :live, label: false, :class => "hidden", :wrapper => false, :checked => false %>
          <%= button_tag(type: 'submit', class: 'col s12 btn deep-orange accent-3 waves-effect waves-light', :data => { :position => "top", :delay => "50", :tooltip => "End #{@campaign.title}" }) do %>
            <i class="fa fa-ban"></i> <%= "END" %>
          <% end %>
        <% end %>
      <% else %>
        <%= simple_form_for @campaign, html: { class: "col s12 m6 l2 start-campaign"} do |f| %>
          <%= f.check_box :live, label: false, :class => "hidden", :wrapper => false, :checked => true %>
          <%= button_tag(type: 'submit', class: 'col s12 btn green accent-4 waves-effect waves-light', :data => { :position => "top", :delay => "50", :tooltip => "Set #{@campaign.title}" }) do %>
            <i class="fa fa-thumbs-up"></i> <%= "GO LIVE" %>
          <% end %>
        <% end %>
      <% end %>
      <%= link_to slideshow_path(campaign_id: @campaign.id), class: 'col s12 m6 l2 btn waves-effect waves-light orange darken-4', :data => { :position => "bottom", :delay => "50", :tooltip => "View a slideshow of all entries" } do %>
        <i class="fa fa-photo"></i> SLIDESHOW
      <% end %>
      <%= link_to random_winner_path(campaign_id: @campaign.id), class: 'col s12 m6 l2 offset-m3 btn waves-effect waves-light green darken-4', :data => { :position => "top", :delay => "50", :tooltip => "Pick a random winner" } do %>
        <i class="fa fa-trophy"></i> WINNER
      <% end %>
    </div>
    <div class="col s12">
      <%= form_tag(campaign_path(@campaign, @campaign.posts), :method => "get", id: "search-form") do %>
        <div class="input-field col s12">
          <i class="material-icons prefix">search</i>
          <%= text_area_tag :search, params[:search], id: 'icon_prefix2', :class => 'materialize-textarea' %>
          <label for="icon_prefix2">Search by Email or Name</label>
        </div>
        <div class="input-field col s12">
          <%= submit_tag "Search", :class => 'col s12 m6 offset-m3 l2 offset-l5 search-btn btn grey darken-4' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if params[:search] && params[:search].length > 0 && !@posts.present? %>
  <script>
    window.onload = function () {
      var msg = "No email address or name found containing the search terms \'<%= params[:search]%>\'";
      Materialize.toast(msg, 5000, 'red darken-4');
    }
  </script>
<% end %>

app/views/campaigns/_campaign.html.erb
<div class="col l12 m12 s12 xs12">
	<ul class="collection">
		<% @campaigns.each do |campaign| %>
			<li class="collection-item avatar">
				<%= link_to campaign_path(campaign) do %>
					<% if campaign.video? %>
						<% if campaign.video_processing? %>
							<%= image_tag "red-preloader.gif", :alt => "preloader", class: 'circle', :data => { :position => "bottom", :delay => "50", :tooltip => "Thumbnail is processing..." } %>
						<% else %>
							<% if campaign.live %>
								<%= image_tag campaign.video.thumb.url, class: 'circle live-campaign', :data => { :position => "bottom", :delay => "50", :tooltip => "This campaign is LIVE!" } %>
							<% else %>
								<%= image_tag campaign.video.thumb.url, class: 'circle dead-campaign', :data => { :position => "bottom", :delay => "50", :tooltip => "This campaign is NOT live!" } %>
							<% end %>
						<% end %>
					<% elsif campaign.feature? %>
						<% if campaign.feature_processing? %>
							<%= image_tag "red-preloader.gif", :alt => "preloader", class: 'circle', :data => { :position => "bottom", :delay => "50", :tooltip => "Thumbnail is processing..." } %>
						<% else %>
							<% if campaign.live %>
								<%= image_tag campaign.feature.tiny.url, class: 'circle live-campaign', :data => { :position => "bottom", :delay => "50", :tooltip => "This campaign is LIVE!" } %>
							<% else %>
								<%= image_tag campaign.feature.tiny.url, class: 'circle dead-campaign', :data => { :position => "bottom", :delay => "50", :tooltip => "This campaign NOT live!" } %>
							<% end %>
						<% end %>
					<% else %>
						<%= image_tag "missing-thumb.png", :alt => "missing thumbnail", class: 'circle' %>
					<% end %>
					<span class="title" data-position="bottom" data-delay="50" data-tooltip="Visit <%= campaign.title%>"><b>Title:</b> <%= campaign.title  %></span>
					<p><b>URL:</b> <%= "#{root_url.chomp('/')}#{url_for campaign}" %><p>
					<p><b>Entries:</b> <%= campaign.posts.count %><p>
					<%= link_to campaign_path(campaign), data: {confirm: 'Are you sure?'}, method: :delete, class: 'secondary-content' do %>
						<span class="fa-stack fa-lg" data-position="bottom" data-delay="50" data-tooltip="Delete <%= campaign.title%>">
							<i class="fa fa-circle fa-stack-2x"></i>
							<i class="fa fa-trash fa-stack-1x fa-inverse"></i>
						</span>
					<% end %>
					<%= link_to edit_campaign_path(campaign), class: 'secondary-content edit' do %>
						<span class="fa-stack fa-lg" data-position="top" data-delay="50" data-tooltip="Edit <%= campaign.title%>">
							<i class="fa fa-circle fa-stack-2x"></i>
							<i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
						</span>
					<% end %>
					<a class="copy secondary-content" data-position="bottom" data-delay="50" data-tooltip="Copy link to <%= campaign.title%>" data-clipboard-text="<%= "#{root_url.chomp('/')}#{url_for campaign}" %>">
						<span class="fa-stack fa-lg">
							<i class="fa fa-circle fa-stack-2x"></i>
							<i class="fa fa-clipboard fa-stack-1x fa-inverse"></i>
						</span>
					</a>
				<% end %>
			</li>
		<% end %>
	</ul>
</div>

app/views/campaigns/_campaignanalytics.html.erb
<script>
  var gaCode = '<%= @campaign.analytics %>';
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', gaCode, 'auto');
  ga('send', 'pageview');
</script>

app/views/campaigns/_customcampaignstyles.html.erb
<% if @campaign.top_color && @campaign.bottom_color %>
    <style>
      .gradient {
        /*positioning*/
        position: fixed;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        overflow: auto;
        z-index: -9999;
        /*Gradient*/
        background: -webkit-linear-gradient(<%= @campaign.top_color %>, <%= @campaign.bottom_color %>); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(<%= @campaign.top_color %>, <%= @campaign.bottom_color %>); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(<%= @campaign.top_color %>, <%= @campaign.bottom_color %>); /* For Firefox 3.6 to 15 */
        background: linear-gradient(<%= @campaign.top_color %>, <%= @campaign.bottom_color %>); /* Standard syntax (must be last) */
      }
      .colored-text{
        color: <%= @campaign.text_color %>;
      }
    </style>
    <script type="text/javascript">
        var textShadow = '<%= @campaign.text_shadow %>'
    </script>
<% end %>
<% if user_admin(@user) %>
    <style>
        #campaign-feature{
            margin-top: 0;
        }
    </style>
<% end %>

app/views/campaigns/_entryform.html.erb
<!-- Modal Structure -->
<div id="entryform" class="modal">
	<div class="x-out hide-on-large-only">
		<span class="fa-stack fa-lg">
			<i class="fa fa-circle fa-stack-2x"></i>
			<i class="fa fa-times fa-stack-1x fa-inverse"></i>
		</span>
	</div>
	<div class="modal-content">
		<h4>Submit Your Entry</h4>
		<%= simple_form_for [@campaign, @campaign.posts.build], html: {  class: 'the-wizard' } do |f| %>
			<fieldset>
	        	<h5>Enter Your Full Name</h5>
	        	<p class="wizard-desc">Please give us your first and last name.</p>
		        <div class="input-field col s12">
					<%= f.input :full_name, :input_html => {:autofocus => true} %>
		        </div>
	        </fieldset>
			<fieldset>
      	<h5>Enter Your Email Address</h5>
      	<p class="wizard-desc">Please enter a valid email address.</p>
        <div class="input-field col s12">
			<%= f.input :email_address %>
        </div>
      </fieldset>
      <fieldset>
      	<h5>Enter Your Birthday</h5>
      	<p class="wizard-desc">You must be 13 years or older to enter a submission!</p>
        <div class="input-field col s12">
					<%= f.input :dob, input_html: { class: 'datepicker' }, :label => 'Date of Birth' %>
        </div>
      </fieldset>
			<% if @campaign.campaign_type == "Both Media Types" %>
	      <fieldset>
	      	<h5>Upload A Photo Or Video</h5>
	      	<p class="wizard-desc">Use your camera to upload a photo or a video!</p>
					<div class="file-field input-field col s12">
						<div class="btn grey darken-4">
							<span>IMAGE</span>
							<label class="hidden-label">image upload</label>
							<%= f.file_field :image_url, :accept => "image/*", :capture => "camera" %>
							<%= f.hidden_field :image_url_cache %>
						</div>
						<div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
						</div>
					</div>
					<div class="file-field input-field col s12">
						<div class="btn grey darken-4">
							<span>VIDEO</span>
							<label class="hidden-label">image upload</label>
							<%= f.file_field :video_url, :accept => "video/*", :capture => "camera" %>
						</div>
						<div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
						</div>
						<h6 class="red-text">Video Duration Limit - <%= @duration_limit %></h6>
					</div>
				</fieldset>
			<% elsif @campaign.campaign_type == "Just Photo" %>
				<fieldset>
					<h5>Upload A Photo</h5>
					<p class="wizard-desc">Use your camera to upload a photo!</p>
					<div class="file-field input-field col s12">
						<div class="btn grey darken-4">
							<span>IMAGE</span>
							<label class="hidden-label">image upload</label>
							<%= f.file_field :image_url, :accept => "image/*", :capture => "camera" %>
							<%= f.hidden_field :image_url_cache %>
						</div>
						<div class="file-path-wrapper">
			        <input class="file-path validate" type="text">
						</div>
					</div>
				</fieldset>
			<% elsif @campaign.campaign_type == "Just Video" %>
				<fieldset>
					<h5>Upload A Video</h5>
					<p class="wizard-desc">Use your camera to upload a video!</p>
					<div class="file-field input-field col s12">
						<div class="btn grey darken-4">
							<span>VIDEO</span>
							<label class="hidden-label">image upload</label>
							<%= f.file_field :video_url, :accept => "video/*", :capture => "camera" %>
						</div>
						<div class="file-path-wrapper">
				      <input class="file-path validate" type="text">
						</div>
						<h6 class="red-text">Video Duration Limit - <%= @duration_limit %></h6>
					</div>
				</fieldset>
			<% end %>
			<fieldset>
	        	<h5>Terms Of Service</h5>
	        	<p class="wizard-desc">By submitting a photo or video you agree to our <a href="#">Terms of Service</a>.</p>
			</fieldset>
			<%= f.submit 'Submit' , class: 'btn green add-content darken-4' %>
		<% end %>
	</div>
</div>

app/views/campaigns/_error.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col l8 offset-l2 left-align">
        <h1><strong>Oops...</strong></h1>
      </div>
      <div class="col l8 offset-l2 center-align">
        <h1 class="error-icon"><span class="fa-stack fa-lg">
          <i class="fa fa-user fa-stack-1x"></i>
          <i class="fa fa-ban fa-stack-2x red-text"></i>
        </span></h1>
      </div>
      <div class="col l8 offset-l2 right-align">
        <h3>... something went wrong.</h3>
      </div>
      <div class="col l8 offset-l2 center-align">
        <p>If you are seeing this page and believe it to be an error, please contact the administrator or webmaster. Thank you.</p>
      </div>
    </div>
  </div>
</main>

app/views/campaigns/_postmodals.html.erb
<!-- Modal Structure -->
<% @posts.each do |post| %>
	<div id="<%= "post-#{post.id}" %>" class="modal">
		<div class="modal-content center-align">
			<% if post.image_url? %>
				<img class="responsive-img" src="<%= post.image_url.url %>">
			<% elsif post.video_url? %>
				<video preload="auto" class="vjs-big-play-centered video-js vjs-default-skin vjs-paused vjs-controls-enabled vjs-user-inactive modal-video feed-vid" controls data-setup="{}">
					<source src="<%= post.video_url.url %>" type='video/mp4'>
				</video>
			<% end %>
		</div>
	</div>
<% end %>

app/views/campaigns/_posts.html.erb
<% @posts.each do |post| %>
	<% if post.image_url? %>
		<div class="col l3 m3 s4 xs4 entry-thumb">
			<% if user_admin(current_user) %>
				<%= link_to campaign_post_path(@campaign, post), data: { confirm: 'Are you sure?' }, method: :delete, class: 'post-delete', :remote => true, :data => { :position => "top", :delay => "50", :tooltip => "Delete post from #{post.full_name}" } do %>
					<span class="fa-stack fa-lg circle hoverable z-depth-1">
					  <i class="fa fa-circle fa-stack-2x red-text text-darken-4"></i>
					  <i class="fa fa-times fa-stack-1x white-text"></i>
					</span>
				<% end %>
			<% end %>
			<div class="card hoverable">
				<div class="card-image">
					<a class="feed-modal-trigger" href="<%= "#post-#{post.id}" %>">
						<img class="<%= "post-#{post.id}" %>" data-processing="<%= post.image_url_processing %>" data-id="<%= post.id %>" data-campaign="<%= post.campaign.friendly_id %>" src="<%= post.image_url.thumb.url %>" data-position="top" data-delay="50" data-tooltip="View post from <%= post.full_name%>">
					</a>
				</div>
			</div>
		</div>
	<% elsif post.video_url? %>
		<div class="col l3 m3 s4 xs4 entry-thumb">
			<% if user_admin(current_user) %>
				<%= link_to campaign_post_path(@campaign, post), data: { confirm: 'Are you sure?' }, method: :delete, class: 'post-delete', :remote => true do %>
					<span class="fa-stack fa-lg circle hoverable z-depth-1">
					  <i class="fa fa-circle fa-stack-2x red-text text-darken-4"></i>
					  <i class="fa fa-times fa-stack-1x white-text"></i>
					</span>
				<% end %>
			<% end %>
			<div class="card hoverable">
				<div class="card-image vid-card">
					<a class="feed-modal-trigger" href="<%= "#post-#{post.id}" %>">
						<img data-processing="<%= post.video_url_processing %>" data-id="<%= post.id %>" data-campaign="<%= post.campaign.friendly_id %>" class="vid-thumb <%= "post-#{post.id}" %>" src="<%= post.video_url.thumb.url %>" data-position="top" data-delay="50" data-tooltip="View post from <%= post.full_name%>">
					</a>
				</div>
			</div>
		</div>
	<% end %>
<% end %>
<div class="col l12 m12 s12 xs12 center-align">
	<%= will_paginate @posts %>
</div>
<%= render 'campaigns/postmodals' %>

app/views/campaigns/edit.html.erb
<main class="new-campaign">
	<div class="container">
    <div class="row">
    <h1>Editing <%= @campaign.title %></h1>
    </div>
		<%= render 'form' %>
	</div>
</main>

app/views/campaigns/index.html.erb
<main class="campaign-index">
	<div class="container">
		<div class="row">
			<div class="col l8">
				<h1>Campaigns</h1>
			</div>
			<div class="col l4">
			  <h1>
					<div class="switch">
					  <label>
					    Help Off
					    <input id="helpers" type="checkbox">
					    <span id="helper-lever" class="lever"></span>
					    Help On
					  </label>
					</div>
			  </h1>
			</div>
		</div>
		<div class="row">
			<%= render partial: 'campaign' %>
			<div class="col l12 m12 s12 xs 12 right-align">
				<%= link_to new_campaign_path, class: 'btn-floating btn-large waves-effect waves-light grey darken-4', :data => { :position => "bottom", :delay => "50", :tooltip => "Create a new Campaign" } do %>
					<i class="material-icons">add</i>
				<% end %>
			</div>
		</div>
	</div>
</main>

app/views/campaigns/new.html.erb
<main class="new-campaign">
  <div class="container">
    <div class="row">
    <h1>Create A New Campaign</h1>
    </div>
    <%= render 'form' %>
  </div>
</main>

app/views/campaigns/show.html.erb
<%= render 'campaignanalytics' %>
<%= render 'customcampaignstyles' %>
<main>
	<div class="container">
		<div class="row">
			<div class="col l3 offset-l1 card-panel hoverable center-align back-link">
				<% if user_admin(@user) %>
						<%= link_to campaigns_path do %>
							<p><i class="fa fa-arrow-left"></i> Back to Campaigns</p>
						<% end %>
				<% end %>
			</div>
			<div class="col l10 offset-l1 m12 s12">
				<div id="campaign-feature" class="card large hoverable">
					<% if @campaign.feature? %>
					<div id="feature" class="card-image center-card-image">
						<%= image_tag( @campaign.feature.url ) %>
					<% elsif @campaign.video? %>
					<div id="feature" class="card-image">
						<%= videojs_rails sources: { mp4: "#{@campaign.video.url}"}, setup: "{}", controls: true, width:"auto", height:"100%", poster: "#{@campaign.video.poster.url}", class: 'vjs-big-play-centered primary-player' %>
					<% end %>
						<span class="card-title campaign-title"><%= @campaign.title %></span>
					</div>
					<div class="card-content">
	          <p><%= @campaign.description %></p>
	        </div>
	        <div class="card-action center-align">
						<%= @campaign.call_to_action %><br>
						<a class="btn waves-effect waves-light grey add-content darken-4 modal-trigger" href="#entryform">Enter Here</a>
					</div>
				</div>
			</div>
		</div>
		<% if user_admin(@user) %>
			<!-- BEGIN ADMIN PANEL -->
				<%= render 'admintools' %>
			<!-- END ADMIN PANEL -->
		<% end %>
		<% if @campaign.entries_visible || user_admin(@user) %>
		<div class="row">
			<div class="col l10 offset-l1">
				<% if user_admin(@user) && !@campaign.live %>
					<h5 class="colored-text">Recent Entries (NOT ACCEPTING ENTRIES!)</h5>
				<% elsif user_admin(@user) && @campaign.live %>
					<h5 class="colored-text">Recent Entries (LIVE!)</h5>
				<% else %>
					<h5 class="colored-text">Recent Entries</h5>
				<% end %>
			</div>
			<div class="col l10 offset-l1">
				<div class = "sort_paginate_ajax">
					<%= render 'campaigns/posts' %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
<!-- 	<div class="parallax-container">
		<div class="parallax">
			<img src="https://s3.amazonaws.com/rdugc/assets/purpleabstract.jpg">
		</div>
	</div> -->

</main>
<%= render 'campaigns/entryform' %>
<div class="gradient"></div>

app/views/campaigns/show.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("posts"))%>");
$('.feed-modal-trigger').leanModal({
	complete: function() {
	    $('video').each(function(){
	      this.player.pause();
	    });
	}
});
imgloader();